"""Compare Brian state exactly except the single input group's generated name.

Dictionary serialization order and Brian's autogenerated PoissonGroup suffix
are bookkeeping. No arrays, RNG state, queued events or clock values are omitted.
"""
import re
import numpy as np


def input_group_name(checkpoint):
    state=checkpoint['terminal']
    names=[k for k in state if re.fullmatch(r'poissongroup(?:_\d+)?',k)]
    if len(names)!=1:raise ValueError('Require exactly one recognized input group')
    return names[0]


def normalized(checkpoint):
    name=input_group_name(checkpoint);root=checkpoint.copy();state=checkpoint['terminal'].copy()
    state['poissongroup']=state.pop(name);root['terminal']=state
    return root


def same_values(a,b):
    if type(a)!=type(b):return False
    if isinstance(a,dict):return a.keys()==b.keys() and all(same_values(a[k],b[k]) for k in a)
    if isinstance(a,(list,tuple)):return len(a)==len(b) and all(same_values(x,y) for x,y in zip(a,b))
    if isinstance(a,np.ndarray):return a.dtype==b.dtype and a.shape==b.shape and np.array_equal(a,b)
    return bool(a==b)


def equivalent(a,b):return same_values(normalized(a),normalized(b))
